/**
 * Stable error codes returned on {@link TelemetryError} instances.
 * @module config/error-codes
 */

const ERROR_CODES = Object.freeze({
  TELEMETRY_ERROR: 'TELEMETRY_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SEARCH_VALIDATION_ERROR: 'SEARCH_VALIDATION_ERROR',
  GUARDRAIL_VIOLATION: 'GUARDRAIL_VIOLATION',
  DATABASE_ERROR: 'DATABASE_ERROR',
  QUERY_TIMEOUT: 'QUERY_TIMEOUT',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
});

const HTTP_STATUS = Object.freeze({
  BAD_REQUEST: 400,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_SERVER_ERROR: 500,
});

module.exports = {
  ERROR_CODES,
  HTTP_STATUS,
};
